// Code generated by MockGen. DO NOT EDIT.
// Source: factory_interfaces.go

// Package mock_internalinterfaces is a generated GoMock package.
package mock_internalinterfaces

import (
	gomock "github.com/golang/mock/gomock"
	runtime "k8s.io/apimachinery/pkg/runtime"
	cache "k8s.io/client-go/tools/cache"
	internalinterfaces "k8s.restdev.com/operators/pkg/client/informers/externalversions/internalinterfaces"
	reflect "reflect"
)

// MockSharedInformerFactory is a mock of SharedInformerFactory interface
type MockSharedInformerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockSharedInformerFactoryMockRecorder
}

// MockSharedInformerFactoryMockRecorder is the mock recorder for MockSharedInformerFactory
type MockSharedInformerFactoryMockRecorder struct {
	mock *MockSharedInformerFactory
}

// NewMockSharedInformerFactory creates a new mock instance
func NewMockSharedInformerFactory(ctrl *gomock.Controller) *MockSharedInformerFactory {
	mock := &MockSharedInformerFactory{ctrl: ctrl}
	mock.recorder = &MockSharedInformerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSharedInformerFactory) EXPECT() *MockSharedInformerFactoryMockRecorder {
	return m.recorder
}

// Start mocks base method
func (m *MockSharedInformerFactory) Start(stopCh <-chan struct{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", stopCh)
}

// Start indicates an expected call of Start
func (mr *MockSharedInformerFactoryMockRecorder) Start(stopCh interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSharedInformerFactory)(nil).Start), stopCh)
}

// InformerFor mocks base method
func (m *MockSharedInformerFactory) InformerFor(obj runtime.Object, newFunc internalinterfaces.NewInformerFunc) cache.SharedIndexInformer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InformerFor", obj, newFunc)
	ret0, _ := ret[0].(cache.SharedIndexInformer)
	return ret0
}

// InformerFor indicates an expected call of InformerFor
func (mr *MockSharedInformerFactoryMockRecorder) InformerFor(obj, newFunc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InformerFor", reflect.TypeOf((*MockSharedInformerFactory)(nil).InformerFor), obj, newFunc)
}
