// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock_scaling is a generated GoMock package.
package mock_scaling

import (
	gomock "github.com/golang/mock/gomock"
	v1alpha1 "k8s.restdev.com/operators/pkg/client/informers/externalversions/scaling/v1alpha1"
	reflect "reflect"
)

// MockInterface is a mock of Interface interface
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// V1alpha1 mocks base method
func (m *MockInterface) V1alpha1() v1alpha1.Interface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "V1alpha1")
	ret0, _ := ret[0].(v1alpha1.Interface)
	return ret0
}

// V1alpha1 indicates an expected call of V1alpha1
func (mr *MockInterfaceMockRecorder) V1alpha1() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "V1alpha1", reflect.TypeOf((*MockInterface)(nil).V1alpha1))
}
