// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock_v1alpha1 is a generated GoMock package.
package mock_v1alpha1

import (
	gomock "github.com/golang/mock/gomock"
	v1alpha1 "k8s.restdev.com/operators/pkg/client/informers/externalversions/scaling/v1alpha1"
	reflect "reflect"
)

// MockInterface is a mock of Interface interface
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// ScheduledScalers mocks base method
func (m *MockInterface) ScheduledScalers() v1alpha1.ScheduledScalerInformer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScheduledScalers")
	ret0, _ := ret[0].(v1alpha1.ScheduledScalerInformer)
	return ret0
}

// ScheduledScalers indicates an expected call of ScheduledScalers
func (mr *MockInterfaceMockRecorder) ScheduledScalers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScheduledScalers", reflect.TypeOf((*MockInterface)(nil).ScheduledScalers))
}
